name: Daily Visual Test

on:
  schedule:
    # Runs 7am every morning
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  live-visual-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.1.0'
      - run: npm i -g pnpm
      - name: Install deps
        run: pnpm install
      - name: Percy Test
        uses: percy/exec-action@v0.3.1
        with:
          command: cypress run --config baseUrl=https://amirha.com --spec "cypress/integration/landingpage"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
